//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeathWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutomaticPayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AutomaticPayment()
        {
            this.AutomaticPaymentLogs = new HashSet<AutomaticPaymentLog>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FK_AccountID { get; set; }
        public Nullable<int> FK_FrequencyID { get; set; }
        public Nullable<int> FK_CategoryID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual TransactionCategory TransactionCategory { get; set; }
        public virtual PaymentFrequency PaymentFrequency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutomaticPaymentLog> AutomaticPaymentLogs { get; set; }
    }
}
