//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeathWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLog
    {
        public int ID { get; set; }
        public Nullable<int> FK_AccountID { get; set; }
        public Nullable<int> FK_TransactionTypeID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public decimal Balance { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
